spring:
  data:
    redis:
      repositories:
        enabled: true
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1910297447@qq.com
    password: yavldmkhhwosbbcb
    protocol: smtp
    properties:
      mail:
        smtp:
        auth: true
        port: 465 # 465 或者 587
        starttls:
          enable: true
          required: true
        ssl:
          enable: true
          trust: smtp.qq.com

  application:
    name: adminvue-base-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8081
  max-http-header-size: 102400

mybatis-plus:
  configuration:
    #配置日志的
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰映射
    map-underscore-to-camel-case: true
  #全局配置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.stu.system.entity




#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#springdoc:
#  api-docs:
#    # 文档地址
#    path: /v3/api-docs
#  group-configs:
#    - group: default
#      # 改成自己的包名
#      packages-to-scan: com.stu
#      paths-to-match: /**
#  swagger-ui:
#    operations-sorter: alpha
#    path: /swagger-ui.html
#    tags-sorter: alpha


